#version 460

#include "../include/constants.glsl"
#include "../include/structs.glsl"
#include "../include/uniforms.glsl"
#include "../include/rays.glsl"
#include "../include/morton.glsl"
#include "../include/STOmath.glsl"

void main(){
    const int it = int(gl_GlobalInvocationID.x);
    if (it >= RAY_BLOCK samplerUniform.rayCount) return;

    const int t = activedBuf.indc[it];
    Ray ray = fetchRayDirect(t);
}